CREATE TABLE IF NOT EXISTS  DASHBOARD(
    id BIGINT NOT NULL AUTO_INCREMENT ,
    creation_date TIMESTAMP NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS TASK(
    id BIGINT NOT NULL AUTO_INCREMENT ,
    description VARCHAR(255) NOT NULL,
    end_date TIMESTAMP,
    start_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    dashboard_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);