DROP TABLE IF EXISTS DASHBOARD;
CREATE TABLE DASHBOARD(
    id BIGINT NOT NULL AUTO_INCREMENT ,
    creation_date TIMESTAMP NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK(
    id BIGINT NOT NULL AUTO_INCREMENT ,
    description VARCHAR(255) NOT NULL,
    end_date TIMESTAMP,
    start_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    dashboard_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO DASHBOARD VALUES  (1, now(), 'Attlasian tasks');
INSERT INTO DASHBOARD VALUES  (2, now(), 'Attlasian tasks 2');

INSERT INTO TASK VALUES (1, 'description 1', NULL, TIMESTAMP '2022-05-26 14:18:00', 'TODO', 1);
INSERT INTO TASK VALUES (2, 'description 2', NULL, TIMESTAMP '2022-05-26 14:18:00', 'TODO', 1);
INSERT INTO TASK VALUES (3, 'description 1', NULL, TIMESTAMP '2022-05-26 14:18:00', 'TODO', 1);
INSERT INTO TASK VALUES (4, 'description 1', NULL, TIMESTAMP '2022-05-26 14:18:00', 'TODO', 2);
INSERT INTO TASK VALUES (5, 'description 1', NULL, TIMESTAMP '2022-05-26 14:18:00', 'TODO', 2);